/**
 * Game sprites and color palette
 */

// Color palette - maps characters to RGB values
window.PALETTE = {
    "a": [113, 0, 81],
    "b": [154, 0, 110],
    "c": [188, 23, 124],
    "d": [218, 89, 181],
    "e": [102, 12, 0],
    "f": [177, 20, 0],
    "g": [216, 75, 57],
    "h": [255, 145, 131],
    "i": [2, 66, 0],
    "j": [4, 132, 0],
    "k": [58, 177, 54],
    "l": [128, 205, 126],
    "m": [181, 89, 9],
    "n": [220, 111, 14],
    "o": [254, 175, 0],
    "p": [252, 200, 83],
    "q": [23, 23, 30],
    "r": [41, 41, 49],
    "s": [217, 220, 255],
    "t": [255, 255, 255],
    "u": [255, 206, 153],
    "v": [254, 182, 106],
    "w": [205, 136, 63],
    "x": [152, 104, 53],
    "y": [105, 65, 24],
    "z": [70, 42, 12],
}

// Sprite data - ASCII art for game objects
window.src = {
    player: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rggggggggggggggggggr",
        "rghhgggggggggggggggr",
        "rghggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggggggggggggggggfgr",
        "rggggggggggggggggfgr",
        "rggggggggggggggggfgr",
        "rggggggggggggggggfgr",
        "rggggggggggggggggfgr",
        "rggggggggggggggggfgr",
        "rggggggggggfffffffgr",
        "rggggggggggggggggggr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    basic: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rttttttttttttttttttr",
        "rtsssssssssssssssstr",
        "rtsttttttttttttttstr",
        "rtststtttttttttststr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtsttttttttttttttstr",
        "rtststtttttttttststr",
        "rtsttttttttttttttstr",
        "rtsssssssssssssssstr",
        "rttttttttttttttttttr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    lockedPinkGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rccccccccccccccccccr",
        "rcddddcccccccccccccr",
        "rcdddccccccccccccccr",
        "rcddccccbbbbcccccccr",
        "rcdccccbbbbbbccccccr",
        "rcdcccbbbbbbbbcccccr",
        "rcccccbbbbbbbbcccccr",
        "rcccccbbbbbbbbcccccr",
        "rccccccbbbbbbccccccr",
        "rcccccccbbbbcccccccr",
        "rcccccccbbbbcccccccr",
        "rccccccbbbbbbccccccr",
        "rccccccbbbbbbccccccr",
        "rcccccbbbbbbbbccccbr",
        "rcccccbbbbbbbbccccbr",
        "rccccccccccccccccbbr",
        "rccccccccccccccccbbr",
        "rccccccccccccccbbbbr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    lockedYellowGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "roooooooooooooooooor",
        "roppppooooooooooooor",
        "ropppoooooooooooooor",
        "roppoooonnnnooooooor",
        "ropoooonnnnnnoooooor",
        "ropooonnnnnnnnooooor",
        "rooooonnnnnnnnooooor",
        "rooooonnnnnnnnooooor",
        "roooooonnnnnnoooooor",
        "rooooooonnnnooooooor",
        "rooooooonnnnooooooor",
        "roooooonnnnnnoooooor",
        "roooooonnnnnnoooooor",
        "rooooonnnnnnnnoooonr",
        "rooooonnnnnnnnoooonr",
        "roooooooooooooooonnr",
        "roooooooooooooooonnr",
        "roooooooooooooonnnnr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    lockedGreenGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rkkkkkkkkkkkkkkkkkkr",
        "rkllllkkkkkkkkkkkkkr",
        "rklllkkkkkkkkkkkkkkr",
        "rkllkkkkjjjjkkkkkkkr",
        "rklkkkkjjjjjjkkkkkkr",
        "rklkkkjjjjjjjjkkkkkr",
        "rkkkkkjjjjjjjjkkkkkr",
        "rkkkkkjjjjjjjjkkkkkr",
        "rkkkkkkjjjjjjkkkkkkr",
        "rkkkkkkkjjjjkkkkkkkr",
        "rkkkkkkkjjjjkkkkkkkr",
        "rkkkkkkjjjjjjkkkkkkr",
        "rkkkkkkjjjjjjkkkkkkr",
        "rkkkkkjjjjjjjjkkkkjr",
        "rkkkkkjjjjjjjjkkkkjr",
        "rkkkkkkkkkkkkkkkkjjr",
        "rkkkkkkkkkkkkkkkkjjr",
        "rkkkkkkkkkkkkkkjjjjr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    lockedRedGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rggggggggggggggggggr",
        "rghhhhgggggggggggggr",
        "rghhhggggggggggggggr",
        "rghhggggffffgggggggr",
        "rghggggffffffggggggr",
        "rghgggffffffffgggggr",
        "rgggggffffffffgggggr",
        "rgggggffffffffgggggr",
        "rggggggffffffggggggr",
        "rgggggggffffgggggggr",
        "rgggggggffffgggggggr",
        "rggggggffffffggggggr",
        "rggggggffffffggggggr",
        "rgggggffffffffggggbr",
        "rgggggffffffffggggfr",
        "rggggggggggggggggffr",
        "rggggggggggggggggffr",
        "rggggggggggggggffffr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    box: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rzxxxxxxxxxxxxxxxxzr",
        "rxzxxxxxxxxxxxxxxzxr",
        "rxxzxxxxxxxxxxxxzxxr",
        "rxxxzzzzzzzzzzzzxxxr",
        "rxxxzyyyyzyyyyzzxxxr",
        "rxxxzyyyzyyyyzyzxxxr",
        "rxxxzyyzyyyyzyyzxxxr",
        "rxxxzyzyyyyzyyyzxxxr",
        "rxxxzzyyyyzyyyyzxxxr",
        "rxxxzyyyyzyyyyzzxxxr",
        "rxxxzyyyzyyyyzyzxxxr",
        "rxxxzyyzyyyyzyyzxxxr",
        "rxxxzyzyyyyzyyyzxxxr",
        "rxxxzzyyyyzyyyyzxxxr",
        "rxxxzzzzzzzzzzzzxxxr",
        "rxxzxxxxxxxxxxxxzxxr",
        "rxzxxxxxxxxxxxxxxzxr",
        "rzxxxxxxxxxxxxxxxxzr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    buttonBase: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rrssssssssssssssssrr",
        "rssssssssssssssssssr",
        "rssrssssssssssssrssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssssssssssssssssssr",
        "rssrsssssssssssrsssr",
        "rssssssssssssssssssr",
        "rrssssssssssssssssrr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    
    //Buttons are 16x16 instead of the usual 20x20. That means the size of their cubes should be 80 pixels, instead of 100.
    pinkButton: [
        " rrrrrrrrrrrrrr",
        "rrccccccccbbbbrr",
        "rccdddddccccbbbr",
        "rcddddddcccccbbr",
        "rcddddddcccccbbr",
        "rcdddddcccccccbr",
        "rcddddccccccccbr",
        "rcdddcccccccccbr",
        "rcccccccccccccbr",
        "rccccccccccccbbr",
        "rbcccccccccccbbr",
        "rbcccccccccccbbr",
        "rbbcccccccccbbbr",
        "rbbbbccccbbbbbbr",
        "rrbbbbbbbbbbbbrr",
        " rrrrrrrrrrrrrr",
    ],
    yellowButton: [
        " rrrrrrrrrrrrrr ",
        "rroooooooonnnnrr",
        "roopppppoooonnnr",
        "roppppppooooonnr",
        "ropppppooooooonr",
        "roppppoooooooonr",
        "ropppooooooooonr",
        "rooooooooooooonr",
        "roooooooooooonnr",
        "rnooooooooooonnr",
        "rnooooooooooonnr",
        "rnnooooooooonnnr",
        "rnnnnoooonnnnnnr",
        "rrnnnnnnnnnnnnrr",
        " rrrrrrrrrrrrrr ",
    ],
    greenButton: [
        " rrrrrrrrrrrrrr ",
        "rrkkkkkkkkjjjjrr",
        "rkklllllkkkkjjjr",
        "rkllllllkkkkkjjr",
        "rkllllllkkkkkjjr",
        "rklllllkkkkkkkjr",
        "rkllllkkkkkkkkjr",
        "rklllkkkkkkkkkjr",
        "rkkkkkkkkkkkkkjr",
        "rkkkkkkkkkkkkjjr",
        "rjkkkkkkkkkkkjjr",
        "rjkkkkkkkkkkkjjr",
        "rjjkkkkkkkkkjjjr",
        "rjjjjkkkkjjjjjjr",
        "rrjjjjjjjjjjjjrr",
        " rrrrrrrrrrrrrr",
    ],
    redButton: [
        " rrrrrrrrrrrrrr ",
        "rrggggggggffffrr",
        "rgghhhhhggggfffr",
        "rghhhhhhgggggffr",
        "rghhhhhhgggggffr",
        "rghhhhhgggggggfr",
        "rghhhhggggggggfr",
        "rghhhgggggggggfr",
        "rgggggggggggggfr",
        "rggggggggggggffr",
        "rfgggggggggggffr",
        "rfgggggggggggffr",
        "rffgggggggggfffr",
        "rffffggggffffffr",
        "rrffffffffffffrr",
        " rrrrrrrrrrrrrr",
    ],
    exit: [
        "rrrrrrrrrrrrrrrrrrr",
        "rrrrrrrrrrrrrrrrrrr",
        "rrrlllllllllllllrrr",
        "rrlllllllllllllllrr",
        "rrlllllllllllllllrr",
        "rrllhhhhhhhhlllllrr",
        "rrlhhhhhhhhhhllllrr",
        "rrhhhhhhhhhhhllllrr",
        "rrhhhhhlllhhhllllrr",
        "rrhhhhlllllhhllllrr",
        "rrhhhhllhhhhhllllrr",
        "rrhhhhlllhhhlllllrr",
        "rrhhhhlllllllllllrr",
        "rrhhhhllllllllllhrr",
        "rrhhhhhllllllllhhrr",
        "rrhhhhhhhhhhhhhhhrr",
        "rrhhhhhhhhhhhhhhhrr",
        "rrrhhhhhhhhhhhhhrrr",
        "rrrrrrrrrrrrrrrrrrr",
        "rrrrrrrrrrrrrrrrrrr",
    ],
    
    pinkPortal: [
        "rrrrrrrrrrrrrrrr",
        "rrbbbbbbbbbbbbrr",
        "rbbccccccccccbbr",
        "rbccbbbbbbbbccbr",
        "rbcbbccccccbbcbr",
        "rbcbccbbbbccbcbr",
        "rbcbcbbccbbcbcbr",
        "rbcbcbccccbcbcbr",
        "rbcbcbccccbcbcbr",
        "rbcbcbbccbbcbcbr",
        "rbcbccbbbbccbcbr",
        "rbcbbccccccbbcbr",
        "rbccbbbbbbbbccbr",
        "rbbccccccccccbbr",
        "rrbbbbbbbbbbbbrr",
        "rrrrrrrrrrrrrrrr",
    ],
    yellowPortal: [
        "rrrrrrrrrrrrrrrr",
        "rrnnnnnnnnnnnnrr",
        "rnnoooooooooonnr",
        "rnoonnnnnnnnoonr",
        "rnonnoooooonnonr",
        "rnonoonnnnoononr",
        "rnononnoonnononr",
        "rnononoooonononr",
        "rnononoooonononr",
        "rnononnoonnononr",
        "rnonoonnnnoononr",
        "rnonnoooooonnonr",
        "rnoonnnnnnnnoonr",
        "rnnoooooooooonnr",
        "rrnnnnnnnnnnnnrr",
        "rrrrrrrrrrrrrrrr",
    ],
    greenPortal: [
        "rrrrrrrrrrrrrrrr",
        "rrkkkkkkkkkkkkrr",
        "rkkjjjjjjjjjjkkr",
        "rkjjkkkkkkkkjjkr",
        "rkjkkjjjjjjkkjkr",
        "rkjkjjkkkkjjkjkr",
        "rkjkjkkjjkkjkjkr",
        "rkjkjkjjjjkjkjkr",
        "rkjkjkjjjjkjkjkr",
        "rkjkjkkjjkkjkjkr",
        "rkjkjjkkkkjjkjkr",
        "rkjkkjjjjjjkkjkr",
        "rkjjkkkkkkkkjjkr",
        "rkkjjjjjjjjjjkkr",
        "rrkkkkkkkkkkkkrr",
        "rrrrrrrrrrrrrrrr",
    ],
    redPortal: [
        "rrrrrrrrrrrrrrrr",
        "rrffffffffffffrr",
        "rffggggggggggffr",
        "rfggffffffffggfr",
        "rfgffggggggffgfr",
        "rfgfggffffggfgfr",
        "rfgfgffggffgfgfr",
        "rfgfgfggggfgfgfr",
        "rfgfgfggggfgfgfr",
        "rfgfgffggffgfgfr",
        "rfgfggffffggfgfr",
        "rfgffggggggffgfr",
        "rfggffffffffggfr",
        "rffggggggggggffr",
        "rrffffffffffffrr",
        "rrrrrrrrrrrrrrrr",
    ],
    
    pinkUnGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rccccccccccccccccccr",
        "rccccccccccccccccccr",
        "rccbbccccccccccbbccr",
        "rccbbbccccccccbbbccr",
        "rcccbbbccccccbbbcccr",
        "rccccbbbccccbbbccccr",
        "rcccccbbbccbbbcccccr",
        "rccccccbbbbbbccccccr",
        "rcccccccbbbbcccccccr",
        "rcccccccbbbbcccccccr",
        "rccccccbbbbbbccccccr",
        "rcccccbbbccbbbcccccr",
        "rccccbbbccccbbbccccr",
        "rcccbbbccccccbbbccbr",
        "rccbbbccccccccbbccbr",
        "rccbbccccccccccbcbbr",
        "rccccccccccccccccbbr",
        "rccccccccccccccbbbbr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    yellowUnGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rnnnnnnnnnnnnnnnnnnr",
        "rnnnnnnnnnnnnnnnnnnr",
        "rnnoonnnnnnnnnnoonnr",
        "rnnooonnnnnnnnooonnr",
        "rnnnooonnnnnnooonnnr",
        "rnnnnooonnnnooonnnnr",
        "rnnnnnooonnooonnnnnr",
        "rnnnnnnoooooonnnnnnr",
        "rnnnnnnnoooonnnnnnnr",
        "rnnnnnnnoooonnnnnnnr",
        "rnnnnnnoooooonnnnnnr",
        "rnnnnnooonnooonnnnnr",
        "rnnnnooonnnnooonnnnr",
        "rnnnooonnnnnnooonnor",
        "rnnooonnnnnnnnoonnor",
        "rnnoonnnnnnnnnnonoor",
        "rnnnnnnnnnnnnnnnnoor",
        "rnnnnnnnnnnnnnnoooor",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    greenUnGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rkkkkkkkkkkkkkkkkkkr",
        "rkkkkkkkkkkkkkkkkkkr",
        "rkkjjkkkkkkkkkkjjkkr",
        "rkkjjjkkkkkkkkjjjkkr",
        "rkkkjjjkkkkkkjjjkkkr",
        "rkkkkjjjkkkkjjjkkkkr",
        "rkkkkkjjjkkjjjkkkkkr",
        "rkkkkkkjjjjjjkkkkkkr",
        "rkkkkkkkjjjjkkkkkkkr",
        "rkkkkkkkjjjjkkkkkkkr",
        "rkkkkkkjjjjjjkkkkkkr",
        "rkkkkkjjjkkjjjkkkkkr",
        "rkkkkjjjkkkkjjjkkkkr",
        "rkkkjjjkkkkkkjjjkkjr",
        "rkkjjjkkkkkkkkjjkkjr",
        "rkkjjkkkkkkkkkkjkjjr",
        "rkkkkkkkkkkkkkkkkjjr",
        "rkkkkkkkkkkkkkkjjjjr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
    redUnGate: [
        "rrrrrrrrrrrrrrrrrrrr",
        "rggggggggggggggggggr",
        "rggggggggggggggggggr",
        "rggffggggggggggffggr",
        "rggfffggggggggfffggr",
        "rgggfffggggggfffgggr",
        "rggggfffggggfffggggr",
        "rgggggfffggfffgggggr",
        "rggggggffffffggggggr",
        "rgggggggffffgggggggr",
        "rgggggggffffgggggggr",
        "rggggggffffffggggggr",
        "rgggggfffggfffgggggr",
        "rggggfffggggfffggggr",
        "rgggfffggggggfffggfr",
        "rggfffggggggggffggfr",
        "rggffggggggggggfgffr",
        "rggggggggggggggggffr",
        "rggggggggggggggffffr",
        "rrrrrrrrrrrrrrrrrrrr",
    ],
}

// Container for processed sprite images
window.images = {} 